stateDiagram-v2
direction LR
[*] --> pjejjx
state "exp := # &quot;(&quot; exp &quot;)&quot;\nexp := # &quot;-&quot; exp\nexp := # exp &quot;*&quot; exp\nexp := # exp &quot;+&quot; exp\nexp := # exp &quot;-&quot; exp\nexp := # exp &quot;/&quot; exp\nexp := # number" as pjejjx
pjejjx --> nn6722i: #110;#117;#109;#98;#101;#114;
pjejjx --> nrrqtg0: #34;#45;#34;
pjejjx --> nrxn2yh: #101;#120;#112;
pjejjx --> pufb7ao: #34;#40;#34;
state "exp := number #" as nn6722i
state "exp := &quot;-&quot; # exp\nexp := # &quot;(&quot; exp &quot;)&quot;\nexp := # &quot;-&quot; exp\nexp := # exp &quot;*&quot; exp\nexp := # exp &quot;+&quot; exp\nexp := # exp &quot;-&quot; exp\nexp := # exp &quot;/&quot; exp\nexp := # number" as nrrqtg0
nrrqtg0 --> nn6722i: #110;#117;#109;#98;#101;#114;
nrrqtg0 --> nrrqtg0: #34;#45;#34;
nrrqtg0 --> p5yuny2: #101;#120;#112;
nrrqtg0 --> pufb7ao: #34;#40;#34;
state "exp := exp # &quot;*&quot; exp\nexp := exp # &quot;+&quot; exp\nexp := exp # &quot;-&quot; exp\nexp := exp # &quot;/&quot; exp" as nrxn2yh
nrxn2yh --> n645iu1: #34;#45;#34;
nrxn2yh --> p79pl0p: #34;#43;#34;
nrxn2yh --> nljww1i: #34;#42;#34;
nrxn2yh --> nji0mor: #34;#47;#34;
state "exp := &quot;(&quot; # exp &quot;)&quot;\nexp := # &quot;(&quot; exp &quot;)&quot;\nexp := # &quot;-&quot; exp\nexp := # exp &quot;*&quot; exp\nexp := # exp &quot;+&quot; exp\nexp := # exp &quot;-&quot; exp\nexp := # exp &quot;/&quot; exp\nexp := # number" as pufb7ao
pufb7ao --> nn6722i: #110;#117;#109;#98;#101;#114;
pufb7ao --> nrrqtg0: #34;#45;#34;
pufb7ao --> pfs8fsq: #101;#120;#112;
pufb7ao --> pufb7ao: #34;#40;#34;
state "exp := &quot;-&quot; exp #\nexp := exp # &quot;*&quot; exp\nexp := exp # &quot;+&quot; exp\nexp := exp # &quot;-&quot; exp\nexp := exp # &quot;/&quot; exp" as p5yuny2
p5yuny2 --> n645iu1: #34;#45;#34;
p5yuny2 --> p79pl0p: #34;#43;#34;
p5yuny2 --> nljww1i: #34;#42;#34;
p5yuny2 --> nji0mor: #34;#47;#34;
state "exp := # &quot;(&quot; exp &quot;)&quot;\nexp := # &quot;-&quot; exp\nexp := # exp &quot;*&quot; exp\nexp := # exp &quot;+&quot; exp\nexp := # exp &quot;-&quot; exp\nexp := # exp &quot;/&quot; exp\nexp := # number\nexp := exp &quot;-&quot; # exp" as n645iu1
n645iu1 --> nn6722i: #110;#117;#109;#98;#101;#114;
n645iu1 --> nrrqtg0: #34;#45;#34;
n645iu1 --> nir3ifd: #101;#120;#112;
n645iu1 --> pufb7ao: #34;#40;#34;
state "exp := # &quot;(&quot; exp &quot;)&quot;\nexp := # &quot;-&quot; exp\nexp := # exp &quot;*&quot; exp\nexp := # exp &quot;+&quot; exp\nexp := # exp &quot;-&quot; exp\nexp := # exp &quot;/&quot; exp\nexp := # number\nexp := exp &quot;+&quot; # exp" as p79pl0p
p79pl0p --> nn6722i: #110;#117;#109;#98;#101;#114;
p79pl0p --> nrrqtg0: #34;#45;#34;
p79pl0p --> nia4ngn: #101;#120;#112;
p79pl0p --> pufb7ao: #34;#40;#34;
state "exp := # &quot;(&quot; exp &quot;)&quot;\nexp := # &quot;-&quot; exp\nexp := # exp &quot;*&quot; exp\nexp := # exp &quot;+&quot; exp\nexp := # exp &quot;-&quot; exp\nexp := # exp &quot;/&quot; exp\nexp := # number\nexp := exp &quot;*&quot; # exp" as nljww1i
nljww1i --> nn6722i: #110;#117;#109;#98;#101;#114;
nljww1i --> nrrqtg0: #34;#45;#34;
nljww1i --> ni1n7za: #101;#120;#112;
nljww1i --> pufb7ao: #34;#40;#34;
state "exp := # &quot;(&quot; exp &quot;)&quot;\nexp := # &quot;-&quot; exp\nexp := # exp &quot;*&quot; exp\nexp := # exp &quot;+&quot; exp\nexp := # exp &quot;-&quot; exp\nexp := # exp &quot;/&quot; exp\nexp := # number\nexp := exp &quot;/&quot; # exp" as nji0mor
nji0mor --> nn6722i: #110;#117;#109;#98;#101;#114;
nji0mor --> nrrqtg0: #34;#45;#34;
nji0mor --> nj82de3: #101;#120;#112;
nji0mor --> pufb7ao: #34;#40;#34;
state "exp := &quot;(&quot; exp # &quot;)&quot;\nexp := exp # &quot;*&quot; exp\nexp := exp # &quot;+&quot; exp\nexp := exp # &quot;-&quot; exp\nexp := exp # &quot;/&quot; exp" as pfs8fsq
pfs8fsq --> n645iu1: #34;#45;#34;
pfs8fsq --> pq6mn99: #34;#41;#34;
pfs8fsq --> p79pl0p: #34;#43;#34;
pfs8fsq --> nljww1i: #34;#42;#34;
pfs8fsq --> nji0mor: #34;#47;#34;
state "exp := exp &quot;-&quot; exp #\nexp := exp # &quot;*&quot; exp\nexp := exp # &quot;+&quot; exp\nexp := exp # &quot;-&quot; exp\nexp := exp # &quot;/&quot; exp" as nir3ifd
nir3ifd --> n645iu1: #34;#45;#34;
nir3ifd --> p79pl0p: #34;#43;#34;
nir3ifd --> nljww1i: #34;#42;#34;
nir3ifd --> nji0mor: #34;#47;#34;
state "exp := exp &quot;+&quot; exp #\nexp := exp # &quot;*&quot; exp\nexp := exp # &quot;+&quot; exp\nexp := exp # &quot;-&quot; exp\nexp := exp # &quot;/&quot; exp" as nia4ngn
nia4ngn --> n645iu1: #34;#45;#34;
nia4ngn --> p79pl0p: #34;#43;#34;
nia4ngn --> nljww1i: #34;#42;#34;
nia4ngn --> nji0mor: #34;#47;#34;
state "exp := exp &quot;*&quot; exp #\nexp := exp # &quot;*&quot; exp\nexp := exp # &quot;+&quot; exp\nexp := exp # &quot;-&quot; exp\nexp := exp # &quot;/&quot; exp" as ni1n7za
ni1n7za --> n645iu1: #34;#45;#34;
ni1n7za --> p79pl0p: #34;#43;#34;
ni1n7za --> nljww1i: #34;#42;#34;
ni1n7za --> nji0mor: #34;#47;#34;
state "exp := exp &quot;/&quot; exp #\nexp := exp # &quot;*&quot; exp\nexp := exp # &quot;+&quot; exp\nexp := exp # &quot;-&quot; exp\nexp := exp # &quot;/&quot; exp" as nj82de3
nj82de3 --> n645iu1: #34;#45;#34;
nj82de3 --> p79pl0p: #34;#43;#34;
nj82de3 --> nljww1i: #34;#42;#34;
nj82de3 --> nji0mor: #34;#47;#34;
state "exp := &quot;(&quot; exp &quot;)&quot; #" as pq6mn99