stateDiagram-v2
direction LR
[*] --> pxlgk
state "0#exp:'(',exp,')'\n0#exp:'-',exp\n0#exp:exp,'*',exp\n0#exp:exp,'+',exp\n0#exp:exp,'-',exp\n0#exp:exp,'/',exp\n0#exp:number" as pxlgk
pxlgk --> n748w88: #110;#117;#109;#98;#101;#114;
pxlgk --> nmfxz8j: #39;#45;#39;
pxlgk --> plrq2mt: #101;#120;#112;
pxlgk --> p45pzbv: #39;#40;#39;
state "1#exp:number" as n748w88
state "0#exp:'(',exp,')'\n0#exp:'-',exp\n0#exp:exp,'*',exp\n0#exp:exp,'+',exp\n0#exp:exp,'-',exp\n0#exp:exp,'/',exp\n0#exp:number\n1#exp:'-',exp" as nmfxz8j
nmfxz8j --> n748w88: #110;#117;#109;#98;#101;#114;
nmfxz8j --> nmfxz8j: #39;#45;#39;
nmfxz8j --> pm6h9n3: #101;#120;#112;
nmfxz8j --> p45pzbv: #39;#40;#39;
state "1#exp:exp,'*',exp\n1#exp:exp,'+',exp\n1#exp:exp,'-',exp\n1#exp:exp,'/',exp" as plrq2mt
plrq2mt --> njhprch: #39;#45;#39;
plrq2mt --> nkft04v: #39;#43;#39;
plrq2mt --> nkwumj2: #39;#42;#39;
plrq2mt --> nijmik3: #39;#47;#39;
state "0#exp:'(',exp,')'\n0#exp:'-',exp\n0#exp:exp,'*',exp\n0#exp:exp,'+',exp\n0#exp:exp,'-',exp\n0#exp:exp,'/',exp\n0#exp:number\n1#exp:'(',exp,')'" as p45pzbv
p45pzbv --> n748w88: #110;#117;#109;#98;#101;#114;
p45pzbv --> nmfxz8j: #39;#45;#39;
p45pzbv --> pnmrvt9: #101;#120;#112;
p45pzbv --> p45pzbv: #39;#40;#39;
state "1#exp:exp,'*',exp\n1#exp:exp,'+',exp\n1#exp:exp,'-',exp\n1#exp:exp,'/',exp\n2#exp:'-',exp" as pm6h9n3
pm6h9n3 --> njhprch: #39;#45;#39;
pm6h9n3 --> nkft04v: #39;#43;#39;
pm6h9n3 --> nkwumj2: #39;#42;#39;
pm6h9n3 --> nijmik3: #39;#47;#39;
state "0#exp:'(',exp,')'\n0#exp:'-',exp\n0#exp:exp,'*',exp\n0#exp:exp,'+',exp\n0#exp:exp,'-',exp\n0#exp:exp,'/',exp\n0#exp:number\n2#exp:exp,'-',exp" as njhprch
njhprch --> n748w88: #110;#117;#109;#98;#101;#114;
njhprch --> nmfxz8j: #39;#45;#39;
njhprch --> nnuv3: #101;#120;#112;
njhprch --> p45pzbv: #39;#40;#39;
state "0#exp:'(',exp,')'\n0#exp:'-',exp\n0#exp:exp,'*',exp\n0#exp:exp,'+',exp\n0#exp:exp,'-',exp\n0#exp:exp,'/',exp\n0#exp:number\n2#exp:exp,'+',exp" as nkft04v
nkft04v --> n748w88: #110;#117;#109;#98;#101;#114;
nkft04v --> nmfxz8j: #39;#45;#39;
nkft04v --> nyr3nh: #101;#120;#112;
nkft04v --> p45pzbv: #39;#40;#39;
state "0#exp:'(',exp,')'\n0#exp:'-',exp\n0#exp:exp,'*',exp\n0#exp:exp,'+',exp\n0#exp:exp,'-',exp\n0#exp:exp,'/',exp\n0#exp:number\n2#exp:exp,'*',exp" as nkwumj2
nkwumj2 --> n748w88: #110;#117;#109;#98;#101;#114;
nkwumj2 --> nmfxz8j: #39;#45;#39;
nkwumj2 --> n1fsq1o: #101;#120;#112;
nkwumj2 --> p45pzbv: #39;#40;#39;
state "0#exp:'(',exp,')'\n0#exp:'-',exp\n0#exp:exp,'*',exp\n0#exp:exp,'+',exp\n0#exp:exp,'-',exp\n0#exp:exp,'/',exp\n0#exp:number\n2#exp:exp,'/',exp" as nijmik3
nijmik3 --> n748w88: #110;#117;#109;#98;#101;#114;
nijmik3 --> nmfxz8j: #39;#45;#39;
nijmik3 --> pxfdxb: #101;#120;#112;
nijmik3 --> p45pzbv: #39;#40;#39;
state "1#exp:exp,'*',exp\n1#exp:exp,'+',exp\n1#exp:exp,'-',exp\n1#exp:exp,'/',exp\n2#exp:'(',exp,')'" as pnmrvt9
pnmrvt9 --> njhprch: #39;#45;#39;
pnmrvt9 --> pmiv7cz: #39;#41;#39;
pnmrvt9 --> nkft04v: #39;#43;#39;
pnmrvt9 --> nkwumj2: #39;#42;#39;
pnmrvt9 --> nijmik3: #39;#47;#39;
state "1#exp:exp,'*',exp\n1#exp:exp,'+',exp\n1#exp:exp,'-',exp\n1#exp:exp,'/',exp\n3#exp:exp,'-',exp" as nnuv3
nnuv3 --> njhprch: #39;#45;#39;
nnuv3 --> nkft04v: #39;#43;#39;
nnuv3 --> nkwumj2: #39;#42;#39;
nnuv3 --> nijmik3: #39;#47;#39;
state "1#exp:exp,'*',exp\n1#exp:exp,'+',exp\n1#exp:exp,'-',exp\n1#exp:exp,'/',exp\n3#exp:exp,'+',exp" as nyr3nh
nyr3nh --> njhprch: #39;#45;#39;
nyr3nh --> nkft04v: #39;#43;#39;
nyr3nh --> nkwumj2: #39;#42;#39;
nyr3nh --> nijmik3: #39;#47;#39;
state "1#exp:exp,'*',exp\n1#exp:exp,'+',exp\n1#exp:exp,'-',exp\n1#exp:exp,'/',exp\n3#exp:exp,'*',exp" as n1fsq1o
n1fsq1o --> njhprch: #39;#45;#39;
n1fsq1o --> nkft04v: #39;#43;#39;
n1fsq1o --> nkwumj2: #39;#42;#39;
n1fsq1o --> nijmik3: #39;#47;#39;
state "1#exp:exp,'*',exp\n1#exp:exp,'+',exp\n1#exp:exp,'-',exp\n1#exp:exp,'/',exp\n3#exp:exp,'/',exp" as pxfdxb
pxfdxb --> njhprch: #39;#45;#39;
pxfdxb --> nkft04v: #39;#43;#39;
pxfdxb --> nkwumj2: #39;#42;#39;
pxfdxb --> nijmik3: #39;#47;#39;
state "3#exp:'(',exp,')'" as pmiv7cz