stateDiagram-v2
direction LR
[*] --> nsb81qh
state "0#array:'[',']'\n0#array:'[',value,']'\n0#array:'[',value,__0,']'\n0#object:'{','}'\n0#object:'{',object_item,'}'\n0#object:'{',object_item,__1,'}'\n0#value:array\n0#value:false\n0#value:null\n0#value:number\n0#value:object\n0#value:string\n0#value:true" as nsb81qh
nsb81qh --> prguybw: #115;#116;#114;#105;#110;#103;
nsb81qh --> pp43amc: #110;#117;#109;#98;#101;#114;
nsb81qh --> pl3ecg9: #116;#114;#117;#101;
nsb81qh --> pefc2vc: #102;#97;#108;#115;#101;
nsb81qh --> pl3akjm: #110;#117;#108;#108;
nsb81qh --> ppamyyi: #111;#98;#106;#101;#99;#116;
nsb81qh --> pecw2pq: #97;#114;#114;#97;#121;
nsb81qh --> poucdee: #39;#91;#39;
nsb81qh --> nwemcqh: #39;#123;#39;
state "1#value:string" as prguybw
state "1#value:number" as pp43amc
state "1#value:true" as pl3ecg9
state "1#value:false" as pefc2vc
state "1#value:null" as pl3akjm
state "1#value:object" as ppamyyi
state "1#value:array" as pecw2pq
state "0#array:'[',']'\n0#array:'[',value,']'\n0#array:'[',value,__0,']'\n0#object:'{','}'\n0#object:'{',object_item,'}'\n0#object:'{',object_item,__1,'}'\n0#value:array\n0#value:false\n0#value:null\n0#value:number\n0#value:object\n0#value:string\n0#value:true\n1#array:'[',']'\n1#array:'[',value,']'\n1#array:'[',value,__0,']'" as poucdee
poucdee --> prguybw: #115;#116;#114;#105;#110;#103;
poucdee --> pp43amc: #110;#117;#109;#98;#101;#114;
poucdee --> pl3ecg9: #116;#114;#117;#101;
poucdee --> pefc2vc: #102;#97;#108;#115;#101;
poucdee --> pl3akjm: #110;#117;#108;#108;
poucdee --> ppamyyi: #111;#98;#106;#101;#99;#116;
poucdee --> pecw2pq: #97;#114;#114;#97;#121;
poucdee --> poucdee: #39;#91;#39;
poucdee --> pr4pf6c: #118;#97;#108;#117;#101;
poucdee --> prcdwue: #39;#93;#39;
poucdee --> nwemcqh: #39;#123;#39;
state "0#object_item:string@key,':',value\n1#object:'{','}'\n1#object:'{',object_item,'}'\n1#object:'{',object_item,__1,'}'" as nwemcqh
nwemcqh --> p9iolme: #115;#116;#114;#105;#110;#103;
nwemcqh --> pxcjgu2: #111;#98;#106;#101;#99;#116;#95;#105;#116;#101;#109;
nwemcqh --> ntcna36: #39;#125;#39;
state "0#__0:',',value\n0#__0:',',value,__0\n2#array:'[',value,']'\n2#array:'[',value,__0,']'" as pr4pf6c
pr4pf6c --> nark6s0: #95;#95;#48;
pr4pf6c --> pgvsux8: #39;#93;#39;
pr4pf6c --> n3idjoj: #39;#44;#39;
state "2#array:'[',']'" as prcdwue
state "1#object_item:string@key,':',value" as p9iolme
p9iolme --> pypp020: #39;#58;#39;
state "0#__1:',',object_item\n0#__1:',',object_item,__1\n2#object:'{',object_item,'}'\n2#object:'{',object_item,__1,'}'" as pxcjgu2
pxcjgu2 --> pyd27bt: #95;#95;#49;
pxcjgu2 --> nnlhn2k: #39;#125;#39;
pxcjgu2 --> ptxrqbo: #39;#44;#39;
state "2#object:'{','}'" as ntcna36
state "3#array:'[',value,__0,']'" as nark6s0
nark6s0 --> ppwu27l: #39;#93;#39;
state "3#array:'[',value,']'" as pgvsux8
state "0#array:'[',']'\n0#array:'[',value,']'\n0#array:'[',value,__0,']'\n0#object:'{','}'\n0#object:'{',object_item,'}'\n0#object:'{',object_item,__1,'}'\n0#value:array\n0#value:false\n0#value:null\n0#value:number\n0#value:object\n0#value:string\n0#value:true\n1#__0:',',value\n1#__0:',',value,__0" as n3idjoj
n3idjoj --> prguybw: #115;#116;#114;#105;#110;#103;
n3idjoj --> pp43amc: #110;#117;#109;#98;#101;#114;
n3idjoj --> pl3ecg9: #116;#114;#117;#101;
n3idjoj --> pefc2vc: #102;#97;#108;#115;#101;
n3idjoj --> pl3akjm: #110;#117;#108;#108;
n3idjoj --> ppamyyi: #111;#98;#106;#101;#99;#116;
n3idjoj --> pecw2pq: #97;#114;#114;#97;#121;
n3idjoj --> poucdee: #39;#91;#39;
n3idjoj --> n68r46i: #118;#97;#108;#117;#101;
n3idjoj --> nwemcqh: #39;#123;#39;
state "0#array:'[',']'\n0#array:'[',value,']'\n0#array:'[',value,__0,']'\n0#object:'{','}'\n0#object:'{',object_item,'}'\n0#object:'{',object_item,__1,'}'\n0#value:array\n0#value:false\n0#value:null\n0#value:number\n0#value:object\n0#value:string\n0#value:true\n2#object_item:string@key,':',value" as pypp020
pypp020 --> prguybw: #115;#116;#114;#105;#110;#103;
pypp020 --> pp43amc: #110;#117;#109;#98;#101;#114;
pypp020 --> pl3ecg9: #116;#114;#117;#101;
pypp020 --> pefc2vc: #102;#97;#108;#115;#101;
pypp020 --> pl3akjm: #110;#117;#108;#108;
pypp020 --> ppamyyi: #111;#98;#106;#101;#99;#116;
pypp020 --> pecw2pq: #97;#114;#114;#97;#121;
pypp020 --> poucdee: #39;#91;#39;
pypp020 --> nrlbqz0: #118;#97;#108;#117;#101;
pypp020 --> nwemcqh: #39;#123;#39;
state "3#object:'{',object_item,__1,'}'" as pyd27bt
pyd27bt --> p14apa0: #39;#125;#39;
state "3#object:'{',object_item,'}'" as nnlhn2k
state "0#object_item:string@key,':',value\n1#__1:',',object_item\n1#__1:',',object_item,__1" as ptxrqbo
ptxrqbo --> p9iolme: #115;#116;#114;#105;#110;#103;
ptxrqbo --> n7j1oik: #111;#98;#106;#101;#99;#116;#95;#105;#116;#101;#109;
state "4#array:'[',value,__0,']'" as ppwu27l
state "0#__0:',',value\n0#__0:',',value,__0\n2#__0:',',value\n2#__0:',',value,__0" as n68r46i
n68r46i --> no843an: #95;#95;#48;
n68r46i --> n3idjoj: #39;#44;#39;
state "3#object_item:string@key,':',value" as nrlbqz0
state "4#object:'{',object_item,__1,'}'" as p14apa0
state "0#__1:',',object_item\n0#__1:',',object_item,__1\n2#__1:',',object_item\n2#__1:',',object_item,__1" as n7j1oik
n7j1oik --> p6rpth1: #95;#95;#49;
n7j1oik --> ptxrqbo: #39;#44;#39;
state "3#__0:',',value,__0" as no843an
state "3#__1:',',object_item,__1" as p6rpth1