import { Logger } from "../model";
import { ASTNode } from "./ast";

export type AcceptedParserOutput<T> = {
  accept: true;
  /**
   * Current AST nodes.
   */
  buffer: readonly ASTNode<T>[];
  /**
   * Newly generated AST nodes by the current parsing call with error.
   * Empty list if no error generated by the current parsing call.
   */
  errors: readonly ASTNode<T>[];
};

export const rejectedParserOutput = Object.freeze({ accept: false });
export type RejectedParserOutput = typeof rejectedParserOutput;

export type ParserOutput<T> = RejectedParserOutput | AcceptedParserOutput<T>;

/**
 * The `input` will be fed to the lexer.
 */
export type ParseExec<T> = (
  input?:
    | string
    | {
        input?: string;
        /**
         * Stop parsing when the first error is generated.
         * Be ware, this might cause inconsistent buffer state.
         *
         * Default: `false`.
         */
        stopOnError?: boolean;
      }
) => ParserOutput<T>;

// TODO: default T
export interface IParser<T> {
  /**
   * When `debug` is `true`, the parser will use `logger` to log debug info.
   * Default: `false`.
   */
  debug: boolean;
  /**
   * The logger used when `debug` is `true`.
   * Default: `console.log`.
   */
  logger: Logger;
  /**
   * Reset state.
   */
  reset(): this;
  /**
   * Clone a new parser with the same states.
   */
  clone(options?: { debug?: boolean; logger?: Logger }): IParser<T>;
  /**
   * Clone a new parser without states.
   */
  dryClone(options?: { debug?: boolean; logger?: Logger }): IParser<T>;
  /**
   * Feed a string to the lexer.
   */
  feed(input: string): this;
  /**
   * Try to yield an entry NT.
   * Stop when the first entry NT is reduced.
   */
  readonly parse: ParseExec<T>;
  /**
   * Try to reduce till the parser can't accept more.
   * This is useful if your entry NT can also be reduced by other rules.
   */
  readonly parseAll: ParseExec<T>;
  /**
   * Get error AST nodes.
   */
  getErrors(): readonly ASTNode<T>[]; // TODO: use getter
  hasErrors(): boolean;
  /**
   * Current AST nodes.
   */
  getNodes(): readonly ASTNode<T>[]; // TODO: rename to buffer, use getter
  /**
   * Take the first AST node.
   */
  take(): ASTNode<T> | undefined; // TODO: take N
}
