import type { GeneralToken } from "../lexer";
import type { ASTNode } from "./ast";

export type AcceptedParserOutput<
  Kinds extends string,
  ASTData,
  ErrorType,
  TokenType extends GeneralToken,
> = {
  accept: true;
  /**
   * Current AST nodes.
   */
  buffer: readonly ASTNode<Kinds, ASTData, ErrorType, TokenType>[];
  /**
   * Newly generated AST nodes by the current parsing call with error.
   * Empty list if no error generated by the current parsing call.
   */
  errors: readonly ASTNode<Kinds, ASTData, ErrorType, TokenType>[];
};

export const rejectedParserOutput = Object.freeze({ accept: false });
export type RejectedParserOutput = typeof rejectedParserOutput;

export type ParserOutput<
  Kinds extends string,
  ASTData,
  ErrorType,
  TokenType extends GeneralToken,
> =
  | RejectedParserOutput
  | AcceptedParserOutput<Kinds, ASTData, ErrorType, TokenType>;
