on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        run: yarn test:coverage

      - name: Fetch existing docs
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          clean: false
          path: gh-pages

      - name: Move existing docs
        run: |
          mv gh-pages/docs ./docs
          rm -rf gh-pages

      - name: Build Doc & Check Generated README
        run: |
          rm -rf docs/dev
          rm -rf docs/stable
          mv README.md README.md.bk
          yarn build:doc
          diff README.md README.md.bk
          rm README.md.bk

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - run: yarn build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs
          destination_dir: docs
