on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # v20.0.0 is needed for some ecma features like the `v` flag in regex when testing
          node-version: 20

      - name: Install Dependencies
        run: yarn

      - name: Check Generated README
        run: |
          mv README.md README.md.bk
          yarn build:readme
          diff README.md README.md.bk
          rm README.md.bk

      # prepublish will check code format, lint code, run tests, generage coverage report, build dists, and build readme
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
